4-puts:
	gcc -Wall -Werror -Wextra -pedantic -std=gnu89 4-puts.c
5-printf:
	gcc -Wall -Werror -Wextra -pedantic -std=gnu89 5-printf.c
6-size:
	gcc 6-size.c -m32 -o size32 2> /tmp/32
	gcc 6-size.c -m64 -o size64 2> /tmp/64
